spring:
  application:
    name: conference-organizer
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/conference-organizer
    username: sa
    password: Passw0rd
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      
logging:
  level:
    org.springframework: info
server:
  port: 9292
  servlet:
    context-path: /conference-organizer